"""
Self-Improvement Engine — NOVA analyzes its own usage, generates new skills,
and writes them into skills/custom_skills.py. Hot-reloaded automatically.
"""
import ast
import importlib
import inspect
import json
import os
import sys
import time
import threading
import traceback
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional

import requests

from config.settings import (
    OLLAMA_HOST, OLLAMA_MODEL,
    SELF_IMPROVE_ENABLED, SELF_IMPROVE_INTERVAL, SELF_IMPROVE_MIN_INTERACTIONS,
    SELF_IMPROVE_ALLOW_CORE_UPDATES,
    BASE_DIR
)

CUSTOM_SKILLS_PATH = BASE_DIR / "skills" / "custom_skills.py"
SKILLS_DIR = BASE_DIR / "skills"
SELF_IMPROVE_LOG = BASE_DIR / "data" / "self_improvement_log.jsonl"


SKILL_TEMPLATE = '''"""
Auto-generated skill: {name}
Generated: {timestamp}
Description: {description}
"""

def {func_name}(args: dict) -> dict:
    """{description}"""
    {code}
'''


class SelfImprovement:
    def __init__(self, memory, assistant_ref=None):
        self.memory = memory
        self.assistant = assistant_ref
        self._running = False
        self._cycle_count = 0
        self._ensure_skills_file()

    def _ensure_skills_file(self):
        SKILLS_DIR.mkdir(parents=True, exist_ok=True)
        if not CUSTOM_SKILLS_PATH.exists():
            CUSTOM_SKILLS_PATH.write_text(
                '"""\nCustom skills generated by NOVA self-improvement engine.\nDo not edit manually — NOVA manages this file.\n"""\n\n# Skills registry\nSKILLS = {}\n\n\ndef register_skill(name, description, func):\n    SKILLS[name] = {"description": description, "func": func}\n'
            )

    def _write_improvement_log(self, payload: dict):
        try:
            SELF_IMPROVE_LOG.parent.mkdir(parents=True, exist_ok=True)
            with open(SELF_IMPROVE_LOG, "a", encoding="utf-8") as f:
                f.write(json.dumps(payload, default=str) + "\n")
        except Exception as e:
            print(f"  ⚠️  Failed to write self-improvement log: {e}")

    def start(self):
        if not SELF_IMPROVE_ENABLED:
            return
        self._running = True
        thread = threading.Thread(target=self._improvement_loop, daemon=True)
        thread.start()
        print("  🧠 Self-improvement engine started")

    def stop(self):
        self._running = False

    def _improvement_loop(self):
        # Wait for minimum interactions before first run
        while self._running:
            interactions = self.memory.get_total_interactions()
            if interactions >= SELF_IMPROVE_MIN_INTERACTIONS:
                break
            time.sleep(60)

        while self._running:
            try:
                self._run_improvement_cycle()
                self._cycle_count += 1
            except Exception as e:
                print(f"  ⚠️  Self-improvement cycle error: {e}")
            time.sleep(SELF_IMPROVE_INTERVAL)

    def _run_improvement_cycle(self):
        print(f"\n  🔧 Running self-improvement cycle #{self._cycle_count + 1}...")

        # 1. Gather usage data
        stats = self.memory.get_interaction_stats(days=7)
        recent = self.memory.get_recent_interactions(n=30)
        existing_skills = self.memory.get_skills()

        # 2. Read own source for context
        source_summary = self._summarize_own_code()

        # 3. Ask LLM for improvement ideas
        prompt = self._build_improvement_prompt(stats, recent, existing_skills, source_summary)
        response = self._query_llm(prompt)
        if not response:
            return

        # 4. Parse and apply suggestions
        suggestions = self._parse_suggestions(response)
        applied = 0
        for suggestion in suggestions[:3]:  # max 3 per cycle
            if self._apply_suggestion(suggestion):
                applied += 1

        if applied > 0:
            print(f"  ✅ Applied {applied} improvement(s)")
            # Hot reload
            self._reload_skills()

    def _summarize_own_code(self) -> str:
        """Get a brief summary of existing capabilities."""
        core_dir = BASE_DIR / "core"
        summaries = []
        for f in core_dir.glob("*.py"):
            try:
                src = f.read_text(encoding="utf-8")
                # Extract function signatures only
                tree = ast.parse(src)
                funcs = [node.name for node in ast.walk(tree)
                         if isinstance(node, ast.FunctionDef) and not node.name.startswith("_")]
                if funcs:
                    summaries.append(f"{f.name}: {', '.join(funcs[:8])}")
            except:
                pass

        existing_skills = CUSTOM_SKILLS_PATH.read_text(encoding="utf-8") if CUSTOM_SKILLS_PATH.exists() else ""
        return "\n".join(summaries) + "\n\nCustom skills:\n" + existing_skills[:500]

    def _build_improvement_prompt(self, stats: Dict, recent: List, skills: List, source: str) -> str:
        stats_str = json.dumps(stats, indent=2)
        skill_names = [s["skill_name"] for s in skills]

        return f"""You are NOVA's self-improvement module. Analyze usage patterns and propose new Python skills.

Usage stats (last 7 days):
{stats_str}

Existing custom skills: {skill_names}

Current capabilities summary:
{source}

Based on this data, propose 1-3 NEW Python helper functions I should add to improve myself.
Focus on:
- Functions the user seems to need but I don't have yet
- Utility functions that would speed up common tasks
- New integrations or capabilities

For each suggestion, respond in this exact JSON format (array):
[
  {{
    "name": "skill_name",
    "func_name": "function_name",
    "description": "What it does",
    "code": "    # Python code here\\n    # Use args dict for parameters\\n    return {{'success': True, 'result': 'value'}}"
  }}
]

IMPORTANT:
- Code must be valid Python
- Functions take (args: dict) as parameter
- Return a dict
- No imports inside functions (use standard library only, or what's already imported)
- Keep functions simple and focused
- Only return the JSON array, nothing else"""

    def _query_llm(self, prompt: str) -> Optional[str]:
        try:
            resp = requests.post(
                f"{OLLAMA_HOST}/api/generate",
                json={
                    "model": OLLAMA_MODEL,
                    "prompt": prompt,
                    "stream": False,
                    "options": {"temperature": 0.3}
                },
                timeout=60
            )
            if resp.status_code == 200:
                return resp.json().get("response", "")
        except Exception as e:
            print(f"  LLM query failed: {e}")
        return None

    def _parse_suggestions(self, response: str) -> List[Dict]:
        """Parse JSON suggestions from LLM response."""
        try:
            # Find JSON array in response
            start = response.find("[")
            end = response.rfind("]") + 1
            if start >= 0 and end > start:
                json_str = response[start:end]
                return json.loads(json_str)
        except json.JSONDecodeError:
            pass

        # Try to extract individual JSON objects
        suggestions = []
        try:
            import re
            pattern = r'\{[^{}]*"name"[^{}]*\}'
            matches = re.findall(pattern, response, re.DOTALL)
            for m in matches:
                try:
                    suggestions.append(json.loads(m))
                except:
                    pass
        except:
            pass

        return suggestions

    def _apply_suggestion(self, suggestion: Dict) -> bool:
        """Validate and apply a code suggestion."""
        required = ["name", "func_name", "description", "code"]
        if not all(k in suggestion for k in required):
            return False

        name = suggestion["name"]
        func_name = suggestion["func_name"]
        description = suggestion["description"]
        code = suggestion["code"]

        # Validate Python syntax
        try:
            full_code = f"def {func_name}(args: dict):\n{code}"
            ast.parse(full_code)
        except SyntaxError as e:
            print(f"  ⚠️  Syntax error in skill '{name}': {e}")
            return False

        # Determine target file and permissions
        target_file = suggestion.get("target_file")
        if target_file:
            write_path = (BASE_DIR / target_file).resolve()
            if not str(write_path).startswith(str(BASE_DIR.resolve())):
                print(f"  ⚠️  Refusing unsafe target path: {target_file}")
                return False
            if "core" in write_path.parts and not SELF_IMPROVE_ALLOW_CORE_UPDATES:
                print("  ⚠️  Core updates are disabled by SELF_IMPROVE_ALLOW_CORE_UPDATES")
                return False
        else:
            write_path = CUSTOM_SKILLS_PATH

        try:
            existing = write_path.read_text(encoding="utf-8") if write_path.exists() else ""
   # can you fix the indentation in this code snippet? it looks off
            skill_code = f"""


            def {func_name}(args: dict) -> dict:
                ""{description}""
            {code}
            """
            if write_path == CUSTOM_SKILLS_PATH:
                skill_code += f""
                register_skill("{name}", "{description}", {func_name})
                ""

            # Avoid duplicates
            if f'register_skill("{name}"' in existing:
                return False

            with open(write_path, "a", encoding="utf-8") as f:
                f.write(skill_code)

            # Log to DB
            self.memory.add_skill(name, description, full_code)

            # Log to file for audit / review
            self._write_improvement_log({
                "timestamp": datetime.utcnow().isoformat() + "Z",
                "skill_name": name,
                "func_name": func_name,
                "description": description,
                "code": code,
                "source": "self_improvement",
                "target_file": str(write_path.relative_to(BASE_DIR))
            })

            print(f"  ✨ New skill added: {name} — {description} ({write_path})")
            return True
        except Exception as e:
            print(f"  ⚠️  Failed to write skill '{name}': {e}")
            return False

    def _reload_skills(self):
        """Hot-reload the custom skills module."""
        try:
            module_name = "skills.custom_skills"
            if module_name in sys.modules:
                importlib.reload(sys.modules[module_name])
            else:
                import importlib.util
                spec = importlib.util.spec_from_file_location(module_name, CUSTOM_SKILLS_PATH)
                module = importlib.util.module_from_spec(spec)
                sys.modules[module_name] = module
                spec.loader.exec_module(module)
            print("  🔄 Skills reloaded")
        except Exception as e:
            print(f"  ⚠️  Skill reload error: {e}")

    def get_custom_skills(self) -> Dict:
        """Get all custom skills."""
        try:
            import importlib.util
            spec = importlib.util.spec_from_file_location(
                "skills.custom_skills", CUSTOM_SKILLS_PATH
            )
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            return getattr(module, "SKILLS", {})
        except Exception:
            return {}

    def execute_custom_skill(self, skill_name: str, args: Dict) -> Dict:
        """Execute a custom skill by name."""
        skills = self.get_custom_skills()
        if skill_name not in skills:
            return {"error": f"Unknown custom skill: {skill_name}",
                    "available": list(skills.keys())}
        try:
            return skills[skill_name]["func"](args)
        except Exception as e:
            return {"error": str(e)}

    def force_cycle(self) -> str:
        """Manually trigger an improvement cycle."""
        try:
            self._run_improvement_cycle()
            return "Improvement cycle completed"
        except Exception as e:
            return f"Cycle failed: {e}"

    def get_status(self) -> Dict:
        skills = self.get_custom_skills()
        return {
            "enabled": SELF_IMPROVE_ENABLED,
            "cycles_completed": self._cycle_count,
            "custom_skills": list(skills.keys()),
            "next_cycle_in": SELF_IMPROVE_INTERVAL,
            "total_interactions": self.memory.get_total_interactions()
        }