"""
Self-Improvement Engine — NOVA analyses its own usage, generates new skills,
and writes them into skills/custom_skills.py. Hot-reloaded automatically.

Updated to use the same LLM_BACKEND switch as assistant.py so self-improvement
queries go to whichever inference server is active (Ollama, llama.cpp, vLLM).
"""
import ast
import importlib
import json
import os
import sys
import time
import threading
import traceback
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional

import requests

from config.settings import (
    OLLAMA_HOST, OLLAMA_MODEL,
    SELF_IMPROVE_ENABLED, SELF_IMPROVE_INTERVAL, SELF_IMPROVE_MIN_INTERACTIONS,
    SELF_IMPROVE_ALLOW_CORE_UPDATES,
    BASE_DIR, LLM_BACKEND,
    OLLAMA_KEEP_ALIVE,
)

CUSTOM_SKILLS_PATH = BASE_DIR / "skills" / "custom_skills.py"
SKILLS_DIR = BASE_DIR / "skills"
SELF_IMPROVE_LOG = BASE_DIR / "data" / "self_improvement_log.jsonl"


class SelfImprovement:
    def __init__(self, memory, assistant_ref=None):
        self.memory = memory
        self.assistant = assistant_ref
        self._running = False
        self._cycle_count = 0
        self._ensure_skills_file()

    def _ensure_skills_file(self):
        SKILLS_DIR.mkdir(parents=True, exist_ok=True)
        if not CUSTOM_SKILLS_PATH.exists():
            CUSTOM_SKILLS_PATH.write_text(
                '"""\nCustom skills generated by NOVA self-improvement engine.\n"""\n\n'
                '# Skills registry\nSKILLS = {}\n\n\n'
                'def register_skill(name, description, func):\n'
                '    SKILLS[name] = {"description": description, "func": func}\n'
            )

    def _write_improvement_log(self, payload: dict):
        try:
            SELF_IMPROVE_LOG.parent.mkdir(parents=True, exist_ok=True)
            with open(SELF_IMPROVE_LOG, "a", encoding="utf-8") as f:
                f.write(json.dumps(payload, default=str) + "\n")
        except Exception as e:
            print(f"  ⚠️  Failed to write self-improvement log: {e}")

    def start(self):
        if not SELF_IMPROVE_ENABLED:
            return
        self._running = True
        threading.Thread(target=self._improvement_loop, daemon=True).start()
        print("  🧠 Self-improvement engine started")

    def stop(self):
        self._running = False

    def _improvement_loop(self):
        while self._running:
            if self.memory.get_total_interactions() >= SELF_IMPROVE_MIN_INTERACTIONS:
                break
            time.sleep(60)
        while self._running:
            try:
                self._run_improvement_cycle()
                self._cycle_count += 1
            except Exception as e:
                print(f"  ⚠️  Self-improvement cycle error: {e}")
            time.sleep(SELF_IMPROVE_INTERVAL)

    def _run_improvement_cycle(self):
        print(f"\n  🔧 Running self-improvement cycle #{self._cycle_count + 1}...")
        stats = self.memory.get_interaction_stats(days=7)
        recent = self.memory.get_recent_interactions(n=30)
        existing_skills = self.memory.get_skills()
        source_summary = self._summarize_own_code()
        prompt = self._build_improvement_prompt(stats, recent, existing_skills, source_summary)
        response = self._query_llm(prompt)
        if not response:
            return
        suggestions = self._parse_suggestions(response)
        applied = 0
        for suggestion in suggestions[:3]:
            if self._apply_suggestion(suggestion):
                applied += 1
        if applied > 0:
            print(f"  ✅ Applied {applied} improvement(s)")
            self._reload_skills()

    def _summarize_own_code(self) -> str:
        core_dir = BASE_DIR / "core"
        summaries = []
        for f in core_dir.glob("*.py"):
            try:
                src = f.read_text(encoding="utf-8")
                tree = ast.parse(src)
                funcs = [node.name for node in ast.walk(tree)
                         if isinstance(node, ast.FunctionDef) and not node.name.startswith("_")]
                if funcs:
                    summaries.append(f"{f.name}: {', '.join(funcs[:8])}")
            except Exception:
                pass
        existing = CUSTOM_SKILLS_PATH.read_text(encoding="utf-8") if CUSTOM_SKILLS_PATH.exists() else ""
        return "\n".join(summaries) + "\n\nCustom skills:\n" + existing[:500]

    def _build_improvement_prompt(self, stats: Dict, recent: List,
                                  skills: List, source: str) -> str:
        return f"""You are NOVA's self-improvement module. Analyse usage patterns and propose new Python skills.

Usage stats (last 7 days):
{json.dumps(stats, indent=2)}

Existing custom skills: {[s["skill_name"] for s in skills]}

Current capabilities summary:
{source}

Propose 1-3 NEW Python helper functions to improve NOVA.
Focus on gaps in capabilities, utility functions, new integrations.

Respond ONLY with a JSON array:
[
  {{
    "name": "skill_name",
    "func_name": "function_name",
    "description": "What it does",
    "code": "    result = args.get('input', '')\\n    return {{'success': True, 'result': result}}"
  }}
]

Rules:
- Valid Python only
- Functions take (args: dict) as parameter and return a dict
- No imports inside functions (use only stdlib)
- Simple and focused
- ONLY return the JSON array, nothing else"""

    def _query_llm(self, prompt: str) -> Optional[str]:
        """
        Query the active LLM backend for a non-streaming completion.

        Ollama   → POST /api/generate   (native, stream:false)
        Others   → POST /v1/chat/completions  (OpenAI-compat, stream:false)
        """
        try:
            if LLM_BACKEND == "ollama":
                resp = requests.post(
                    f"{OLLAMA_HOST}/api/generate",
                    json={
                        "model": OLLAMA_MODEL,
                        "prompt": prompt,
                        "stream": False,
                        "keep_alive": OLLAMA_KEEP_ALIVE,
                        "options": {"temperature": 0.3},
                    },
                    timeout=60,
                )
                if resp.status_code == 200:
                    return resp.json().get("response", "")
            else:
                # OpenAI-compatible non-streaming completion
                resp = requests.post(
                    f"{OLLAMA_HOST}/v1/chat/completions",
                    json={
                        "model": OLLAMA_MODEL,
                        "stream": False,
                        "temperature": 0.3,
                        "max_tokens": 1024,
                        "messages": [{"role": "user", "content": prompt}],
                    },
                    timeout=60,
                )
                if resp.status_code == 200:
                    return (resp.json()
                            .get("choices", [{}])[0]
                            .get("message", {})
                            .get("content", ""))
        except Exception as e:
            print(f"  LLM query failed: {e}")
        return None

    def _parse_suggestions(self, response: str) -> List[Dict]:
        try:
            start = response.find("[")
            end   = response.rfind("]") + 1
            if start >= 0 and end > start:
                return json.loads(response[start:end])
        except json.JSONDecodeError:
            pass
        suggestions = []
        try:
            import re
            for m in re.findall(r'\{[^{}]*"name"[^{}]*\}', response, re.DOTALL):
                try:
                    suggestions.append(json.loads(m))
                except Exception:
                    pass
        except Exception:
            pass
        return suggestions

    def _apply_suggestion(self, suggestion: Dict) -> bool:
        required = ["name", "func_name", "description", "code"]
        if not all(k in suggestion for k in required):
            return False

        name        = suggestion["name"]
        func_name   = suggestion["func_name"]
        description = suggestion["description"].replace('"', "'")
        code        = suggestion["code"]

        try:
            ast.parse(f"def {func_name}(args: dict):\n{code}")
        except SyntaxError as e:
            print(f"  ⚠️  Syntax error in skill '{name}': {e}")
            return False

        target_file = suggestion.get("target_file")
        if target_file:
            write_path = (BASE_DIR / target_file).resolve()
            if not str(write_path).startswith(str(BASE_DIR.resolve())):
                print(f"  ⚠️  Refusing unsafe path: {target_file}")
                return False
            if "core" in write_path.parts and not SELF_IMPROVE_ALLOW_CORE_UPDATES:
                print("  ⚠️  Core updates disabled")
                return False
        else:
            write_path = CUSTOM_SKILLS_PATH

        try:
            existing = write_path.read_text(encoding="utf-8") if write_path.exists() else ""
            if f'register_skill("{name}"' in existing or f"def {func_name}(" in existing:
                return False

            lines = ["", "",
                     f"def {func_name}(args: dict) -> dict:",
                     f'    """{description}"""']
            lines += code.splitlines()
            lines.append("")
            if write_path == CUSTOM_SKILLS_PATH:
                lines.append(f'register_skill("{name}", "{description}", {func_name})')
                lines.append("")

            with open(write_path, "a", encoding="utf-8") as f:
                f.write("\n".join(lines))

            full_code = f"def {func_name}(args: dict):\n{code}"
            self.memory.add_skill(name, description, full_code)
            self._write_improvement_log({
                "timestamp":   datetime.utcnow().isoformat() + "Z",
                "skill_name":  name,
                "func_name":   func_name,
                "description": description,
                "code":        code,
                "source":      "self_improvement",
                "backend":     LLM_BACKEND,
                "target_file": str(write_path.relative_to(BASE_DIR)),
            })
            print(f"  ✨ New skill: {name} — {description}")
            return True
        except Exception as e:
            print(f"  ⚠️  Failed to write skill '{name}': {e}")
            return False

    def _reload_skills(self):
        try:
            module_name = "skills.custom_skills"
            if module_name in sys.modules:
                importlib.reload(sys.modules[module_name])
            else:
                import importlib.util
                spec = importlib.util.spec_from_file_location(module_name, CUSTOM_SKILLS_PATH)
                module = importlib.util.module_from_spec(spec)
                sys.modules[module_name] = module
                spec.loader.exec_module(module)
            print("  🔄 Skills reloaded")
        except Exception as e:
            print(f"  ⚠️  Skill reload error: {e}")

    def get_custom_skills(self) -> Dict:
        try:
            import importlib.util
            spec = importlib.util.spec_from_file_location("skills.custom_skills", CUSTOM_SKILLS_PATH)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            return getattr(module, "SKILLS", {})
        except Exception:
            return {}

    def execute_custom_skill(self, skill_name: str, args: Dict) -> Dict:
        skills = self.get_custom_skills()
        if skill_name not in skills:
            return {"error": f"Unknown custom skill: {skill_name}",
                    "available": list(skills.keys())}
        try:
            return skills[skill_name]["func"](args)
        except Exception as e:
            return {"error": str(e)}

    def force_cycle(self) -> str:
        try:
            self._run_improvement_cycle()
            return "Improvement cycle completed"
        except Exception as e:
            return f"Cycle failed: {e}"

    def get_status(self) -> Dict:
        skills = self.get_custom_skills()
        return {
            "enabled":           SELF_IMPROVE_ENABLED,
            "cycles_completed":  self._cycle_count,
            "custom_skills":     list(skills.keys()),
            "next_cycle_in":     SELF_IMPROVE_INTERVAL,
            "total_interactions":self.memory.get_total_interactions(),
            "llm_backend":       LLM_BACKEND,
        }