"""
Custom skills generated by NOVA self-improvement engine.
NOVA manages this file — but you can add your own skills here too.
"""

# Skills registry
SKILLS = {}


def register_skill(name, description, func):
    SKILLS[name] = {"description": description, "func": func}


# ─── Built-in starter skills ──────────────────────────────────────────────────

def get_weather(args: dict) -> dict:
    """Get current weather for a city using wttr.in (no API key needed)."""
    import requests
    city = args.get("city", "Amsterdam")
    try:
        resp = requests.get(
            f"https://wttr.in/{city}?format=j1",
            timeout=5
        )
        data = resp.json()
        current = data["current_condition"][0]
        return {
            "city": city,
            "temp_c": current["temp_C"],
            "feels_like_c": current["FeelsLikeC"],
            "description": current["weatherDesc"][0]["value"],
            "humidity": current["humidity"],
            "wind_kmph": current["windspeedKmph"]
        }
    except Exception as e:
        return {"error": str(e)}

register_skill("get_weather", "Get current weather for a city", get_weather)


def calculate(args: dict) -> dict:
    """Safe math expression evaluator."""
    import math
    expr = args.get("expression", "")
    try:
        # Safe eval with math functions available
        allowed = {k: getattr(math, k) for k in dir(math) if not k.startswith("_")}
        allowed.update({"abs": abs, "round": round, "min": min, "max": max, "sum": sum})
        result = eval(expr, {"__builtins__": {}}, allowed)
        return {"expression": expr, "result": result}
    except Exception as e:
        return {"error": str(e), "expression": expr}

register_skill("calculate", "Evaluate a math expression", calculate)


def search_web(args: dict) -> dict:
    """Search DuckDuckGo (no API key) and return top results."""
    import requests
    from urllib.parse import quote
    query = args.get("query", "")
    try:
        resp = requests.get(
            f"https://api.duckduckgo.com/?q={quote(query)}&format=json&no_redirect=1",
            timeout=8,
            headers={"User-Agent": "NOVA/1.0"}
        )
        data = resp.json()
        results = []
        if data.get("AbstractText"):
            results.append({"title": "Summary", "text": data["AbstractText"][:300]})
        for r in data.get("RelatedTopics", [])[:3]:
            if isinstance(r, dict) and r.get("Text"):
                results.append({"title": r.get("FirstURL", ""), "text": r["Text"][:200]})
        return {"query": query, "results": results}
    except Exception as e:
        return {"error": str(e)}

register_skill("search_web", "Search the web via DuckDuckGo", search_web)


def read_file(args: dict) -> dict:
    """Read a file from the filesystem."""
    path = args.get("path", "")
    try:
        from pathlib import Path
        p = Path(path).expanduser()
        content = p.read_text(encoding="utf-8")
        return {"path": str(p), "content": content[:3000], "size": len(content)}
    except Exception as e:
        return {"error": str(e)}

register_skill("read_file", "Read a file from disk", read_file)


def write_file(args: dict) -> dict:
    """Write content to a file."""
    from pathlib import Path
    path = args.get("path", "")
    content = args.get("content", "")
    append = args.get("append", False)
    try:
        p = Path(path).expanduser()
        p.parent.mkdir(parents=True, exist_ok=True)
        if append:
            with open(p, "a", encoding="utf-8") as f:
                f.write(content)
        else:
            p.write_text(content, encoding="utf-8")
        return {"success": True, "path": str(p), "bytes_written": len(content)}
    except Exception as e:
        return {"error": str(e)}

register_skill("write_file", "Write content to a file", write_file)


def list_directory(args: dict) -> dict:
    """List files in a directory."""
    from pathlib import Path
    path = args.get("path", ".")
    try:
        p = Path(path).expanduser()
        items = []
        for item in sorted(p.iterdir()):
            items.append({
                "name": item.name,
                "type": "dir" if item.is_dir() else "file",
                "size": item.stat().st_size if item.is_file() else None
            })
        return {"path": str(p), "items": items, "count": len(items)}
    except Exception as e:
        return {"error": str(e)}

register_skill("list_directory", "List files in a directory", list_directory)


def git_status(args: dict) -> dict:
    """Get git status of a repository."""
    import subprocess
    path = args.get("path", ".")
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain", "-b"],
            capture_output=True, text=True, cwd=path, timeout=5
        )
        return {"status": result.stdout, "path": path}
    except Exception as e:
        return {"error": str(e)}

register_skill("git_status", "Get git status of a repository", git_status)


def ip_info(args: dict) -> dict:
    """Get current IP and location info."""
    import requests
    try:
        resp = requests.get("https://ipinfo.io/json", timeout=5)
        return resp.json()
    except Exception as e:
        return {"error": str(e)}

register_skill("ip_info", "Get current IP address and location", ip_info)


def timer(args: dict) -> dict:
    """Set a simple countdown timer (non-blocking, prints when done)."""
    import threading
    import time
    seconds = int(args.get("seconds", 60))
    label = args.get("label", "Timer")
    
    def _countdown():
        time.sleep(seconds)
        print(f"\n  ⏰ {label} — {seconds}s timer complete!")
    
    t = threading.Thread(target=_countdown, daemon=True)
    t.start()
    return {"success": True, "label": label, "seconds": seconds,
            "message": f"Timer set for {seconds} seconds"}

register_skill("timer", "Set a countdown timer", timer)


def unit_convert(args: dict) -> dict:
    """Convert between common units."""
    value = float(args.get("value", 0))
    from_unit = args.get("from", "").lower()
    to_unit = args.get("to", "").lower()
    
    conversions = {
        ("km", "miles"): lambda x: x * 0.621371,
        ("miles", "km"): lambda x: x * 1.60934,
        ("kg", "lbs"): lambda x: x * 2.20462,
        ("lbs", "kg"): lambda x: x * 0.453592,
        ("c", "f"): lambda x: x * 9/5 + 32,
        ("f", "c"): lambda x: (x - 32) * 5/9,
        ("m", "ft"): lambda x: x * 3.28084,
        ("ft", "m"): lambda x: x * 0.3048,
        ("l", "gal"): lambda x: x * 0.264172,
        ("gal", "l"): lambda x: x * 3.78541,
    }
    
    key = (from_unit, to_unit)
    if key in conversions:
        result = conversions[key](value)
        return {"value": value, "from": from_unit, "to": to_unit, "result": round(result, 4)}
    return {"error": f"Conversion {from_unit} → {to_unit} not supported"}

register_skill("unit_convert", "Convert between units", unit_convert)

def create_memo_folder(args: dict) -> dict:
    """Allows the user to create and manage folders within their memos, improving searchability."""
    # Python code here
    # Use args dict for parameters
    return {'success': True, 'result': 'Memo folder created'}

register_skill("memo_organization", "Allows the user to create and manage folders within their memos, improving searchability.", create_memo_folder)


def extract_date_time(args: dict) -> dict:
    """Extracts date and time information from a memo text, useful for filtering and sorting memos."""
    # Python code here
    # Use args dict for parameters
    return {'success': True, 'result': 'Date and time extracted'}

register_skill("data_extraction", "Extracts date and time information from a memo text, useful for filtering and sorting memos.", extract_date_time)


def schedule_reminder(args: dict) -> dict:
    """Allows the user to set a reminder based on text input, integrating with the existing agenda functionality."""
    # Python code here
    # Use args dict for parameters
    return {'success': True, 'result': 'Reminder scheduled'}

register_skill("task_reminder", "Allows the user to set a reminder based on text input, integrating with the existing agenda functionality.", schedule_reminder)
